swagger: "2.0"
info:
  description: "This is a sample server Flights  API."
  version: "1.0.0"
  title: "Flights API"
  contact:
    email: "shwetha_somashekharappa@thbs.com"
host: "localhost:9473"
basePath: "/flightsapi/v1"
schemes:
- "http"
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
paths:
  /flights:
    get:
      tags:
      - "flight"
      summary: "Get All Flights"
      operationId: "getAllFlights"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Flight"
    post:
      tags:
      - "flight"
      summary: "Add new flight Details"
      operationId: "addNewFlight"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "flight object"
          required: true
          schema:
            $ref: "#/definitions/Flight"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Flight"
        400:
          description: "Error Occured. "
  /flights/{flightID}:
    get:
      tags:
      - "flight"
      summary: "Get Flight Details of given flight ID"
      operationId: "getFlightByID"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "flightID"
        type: "integer"
        description: "Flight ID "
        required: true
      responses:
        404:
          description: "Flight not found"
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Flight"
    put:
      tags:
      - "flight"
      summary: "Updates a flight data"
      operationId: "updateFlight"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "flightID"
        in: "path"
        description: "ID of flight that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "body"
        in: "body"
        description: "Updated Flight Data"
        required: true
        schema:
          $ref: "#/definitions/Flight"
      responses:
        200:
          description: "Successfully Updated"
          schema:
            $ref: "#/definitions/Flight"
        400:
          description: "Flight Id does not exists"
    delete:
      tags:
      - "flight"
      summary: "Deletes a Flight"
      operationId: "deleteFlight"
      produces:
      - "text/plain"
      parameters:
      - name: "flightID"
        in: "path"
        description: "Flight id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Flight deleted successfully"
        400:
          description: "Invalid Flight ID"


definitions:
  Flight:
    type: "object"
    properties:
      flightId:
        type: "integer"
        format: "int64"
      airlineName:
        type: "string"
      flightCapacity:
        type: "integer"
        format: "int64"
